apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: myblog-pipeline
description: Cloud Run delivery pipeline for myblog
serialPipeline:
  stages:
    - targetId: dev
      profiles: ["dev"]
    - targetId: prod
      profiles: ["prod"]

